### ISSUE TITLE
Implement 'Next' button functionality in phone authentication flow (task)

### ISSUE THREAD

**Issue by avive** [avive/karmacoin-app#1]
The code is utilizing Flutter UI to implement user phone authentication. Notice the 'Next' buttons in the signup flow. They are currently not working and user must hit 'enter' in order to submit a phone number in the phone screen and an auth-code in the auth-code screen. Implement these buttons to work as expected.

**Comment by Dinokojt7** [comment]
Hi please assign

**Comment by avive** [comment]
We are in the middle of refactoring authentication. Will assign as soon as the code settles a bit in this area.

**Comment by avive** [comment]
This flow is changed for KC2 so this issue is no longer relevant.
